server:
  port: 80

spring:
  application:
    name: cloud-order-consumer

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心,职责是维护实例,并不需要检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
